# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.FloatField(blank=True, null=True)),
                ('polarizability', models.FloatField(blank=True, null=True)),
                ('RI', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MolGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_str', models.CharField(blank=True, max_length=256, verbose_name='Compound Name')),
                ('SMILES_str', models.CharField(blank=True, max_length=256, verbose_name='SMILES string')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publ_RI', models.CharField(blank=True, max_length=128, verbose_name='canonical string of the publication reference')),
                ('publ_density', models.CharField(blank=True, max_length=128, verbose_name='canonical string of the publication reference')),
            ],
        ),
        migrations.AddField(
            model_name='expdata',
            name='mol_graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembddb.MolGraph'),
        ),
        migrations.AddField(
            model_name='expdata',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembddb.Publication'),
        ),
    ]
