# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MolProp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop', models.CharField(default='00000', max_length=32, verbose_name='Keyword for property')),
            ],
        ),
        migrations.RemoveField(
            model_name='expdata',
            name='RI',
        ),
        migrations.RemoveField(
            model_name='expdata',
            name='density',
        ),
        migrations.RemoveField(
            model_name='expdata',
            name='polarizability',
        ),
        migrations.AddField(
            model_name='expdata',
            name='value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expdata',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chembddb.MolProp'),
        ),
    ]
