# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0002_auto_20160930_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publ_RI',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='publ_density',
        ),
        migrations.AddField(
            model_name='publication',
            name='publ_str',
            field=models.CharField(blank=True, max_length=128, verbose_name='canonical string of the publication reference'),
        ),
    ]
