# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0004_auto_20161003_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publ_str',
            field=models.CharField(blank=True, max_length=2048, verbose_name='canonical string of the publication reference'),
        ),
    ]
