# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0005_auto_20161004_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='expdata',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='if value is not an integer'),
        ),
    ]
