# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0006_expdata_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_str', models.CharField(blank=True, max_length=256, verbose_name='unit')),
                ('primary_unit', models.BooleanField(default=False, verbose_name='to be used as primary unit while displaying property value')),
                ('prop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chembddb.MolProp')),
            ],
        ),
        migrations.AlterField(
            model_name='expdata',
            name='comment',
            field=models.CharField(blank=True, max_length=256, verbose_name='if value is not a float/number'),
        ),
    ]
