# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0007_auto_20161020_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule_str', models.CharField(max_length=256, verbose_name='Molecule name')),
                ('smiles_str', models.CharField(max_length=256, verbose_name='SMILES str')),
                ('property_str', models.CharField(blank=True, max_length=4096, verbose_name='Encoded Property String')),
                ('user', models.CharField(blank=False, max_length=256, verbose_name='Username'))
            ],
        ),
    ]
