# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0009_auto_20170325_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(blank=True, max_length=32, verbose_name='Keyword for property'),
        ),
    ]
