# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0010_auto_20170327_0439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calcdata',
            name='met',
        ),
        migrations.DeleteModel(
            name='method',
        ),
    ]
