# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0012_auto_20170327_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(default='00000', max_length=32, verbose_name='Keyword for method'),
        ),
    ]
