# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0014_auto_20170328_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chembddb.Unit'),
        ),
    ]
