# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0017_auto_20170601_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
