# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0020_auto_20170602_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='credit',
            field=models.CharField(default='The Hachmann Group', max_length=256, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='data',
            name='met',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chembddb.Method'),
        ),
        migrations.AlterField(
            model_name='data',
            name='value',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='method',
            name='comment',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='details for the method'),
        ),
        migrations.AlterField(
            model_name='method',
            name='method',
            field=models.CharField(db_index=True, default='00000', max_length=32, verbose_name='Keyword for method'),
        ),
        migrations.AlterField(
            model_name='molgraph',
            name='SMILES_str',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='SMILES string'),
        ),
        migrations.AlterField(
            model_name='molprop',
            name='prop',
            field=models.CharField(db_index=True, default='00000', max_length=32, verbose_name='Keyword for property'),
        ),
        migrations.AlterField(
            model_name='molprop',
            name='unit',
            field=models.CharField(db_index=True, default=' ', max_length=32, verbose_name='keyword for unit'),
        ),
        migrations.AlterIndexTogether(
            name='data',
            index_together=set([('mol_graph', 'property', 'value')]),
        ),
    ]
