# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chembddb', '0021_auto_20180405_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='met',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chembddb.Method'),
        ),
    ]
